FROM python:3.10

WORKDIR /usr/src/app/katara_service
ENV PYTHONPATH /usr/src/app/

COPY katara_service/alembic ./alembic
COPY katara_service/controllers ./controllers
COPY katara_service/handlers ./handlers
COPY katara_service/models ./models
COPY katara_service/*.py ./
COPY katara_service/alembic.template ./
COPY katara_service/swagger ./swagger
COPY katara_service/auth_client ./auth_client
COPY katara_service/config_client ./config_client
COPY katara_service/optscale_exceptions ./optscale_exceptions
COPY katara_service/rest_api_client ./rest_api_client
COPY requirements_service.txt ./requirements.txt

RUN pip install -r requirements.txt
RUN python -u write_spec.py

CMD ["python", "-u","/usr/src/app/katara_service/main.py"]
EXPOSE 8935
